// <auto-generated />
using System;
using ExpensesTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpensesTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251021235307_RemoveNotesAddPaymentMethod")]
    partial class RemoveNotesAddPaymentMethod
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ExpensesTracker.Data.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FinancialEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTransferred")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FinancialEntityId");

                    b.HasIndex("UserId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("ExpensesTracker.Data.FinancialEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FinancialEntities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Banco de la Nación Argentina",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Banco Provincia de Buenos Aires",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Banco de Galicia y Buenos Aires",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Banco de la Ciudad de Buenos Aires",
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Banco Patagonia",
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Banco Macro",
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Banco Santander Argentina",
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "Banco BBVA Argentina",
                            Type = 0
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Name = "Banco Credicoop Cooperativo Limitado",
                            Type = 0
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            Name = "Brubank S.A.U.",
                            Type = 0
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            Name = "Ualá Bank S.A.U.",
                            Type = 0
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            Name = "Banco Hipotecario S.A.",
                            Type = 0
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            Name = "Banco de Corrientes S.A.",
                            Type = 0
                        },
                        new
                        {
                            Id = 14,
                            IsActive = true,
                            Name = "Banco de Córdoba S.A.",
                            Type = 0
                        },
                        new
                        {
                            Id = 15,
                            IsActive = true,
                            Name = "Banco BICA S.A.",
                            Type = 0
                        },
                        new
                        {
                            Id = 16,
                            IsActive = true,
                            Name = "Mercado Pago",
                            Type = 1
                        },
                        new
                        {
                            Id = 17,
                            IsActive = true,
                            Name = "Ualá",
                            Type = 1
                        },
                        new
                        {
                            Id = 18,
                            IsActive = true,
                            Name = "Naranja X",
                            Type = 1
                        },
                        new
                        {
                            Id = 19,
                            IsActive = true,
                            Name = "Cuenta DNI",
                            Type = 1
                        },
                        new
                        {
                            Id = 20,
                            IsActive = true,
                            Name = "Personal Pay",
                            Type = 1
                        },
                        new
                        {
                            Id = 21,
                            IsActive = true,
                            Name = "BNA+",
                            Type = 1
                        },
                        new
                        {
                            Id = 22,
                            IsActive = true,
                            Name = "MODO",
                            Type = 1
                        },
                        new
                        {
                            Id = 23,
                            IsActive = true,
                            Name = "Prex",
                            Type = 1
                        },
                        new
                        {
                            Id = 24,
                            IsActive = true,
                            Name = "Claro Pay",
                            Type = 1
                        },
                        new
                        {
                            Id = 25,
                            IsActive = true,
                            Name = "Lemon Cash",
                            Type = 1
                        },
                        new
                        {
                            Id = 26,
                            IsActive = true,
                            Name = "AstroPay",
                            Type = 1
                        },
                        new
                        {
                            Id = 27,
                            IsActive = true,
                            Name = "Moni",
                            Type = 1
                        },
                        new
                        {
                            Id = 28,
                            IsActive = true,
                            Name = "PayMovil",
                            Type = 1
                        },
                        new
                        {
                            Id = 29,
                            IsActive = true,
                            Name = "Pluspagos",
                            Type = 1
                        },
                        new
                        {
                            Id = 30,
                            IsActive = true,
                            Name = "Resimple",
                            Type = 1
                        },
                        new
                        {
                            Id = 31,
                            IsActive = true,
                            Name = "TodoPago",
                            Type = 1
                        },
                        new
                        {
                            Id = 32,
                            IsActive = true,
                            Name = "Valepei",
                            Type = 1
                        },
                        new
                        {
                            Id = 33,
                            IsActive = true,
                            Name = "Billetera País",
                            Type = 1
                        },
                        new
                        {
                            Id = 34,
                            IsActive = true,
                            Name = "Xcoop",
                            Type = 1
                        });
                });

            modelBuilder.Entity("ExpensesTracker.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ExpensesTracker.Data.Expense", b =>
                {
                    b.HasOne("ExpensesTracker.Data.FinancialEntity", "FinancialEntity")
                        .WithMany("Expenses")
                        .HasForeignKey("FinancialEntityId");

                    b.HasOne("ExpensesTracker.Data.User", "User")
                        .WithMany("Expenses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinancialEntity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExpensesTracker.Data.FinancialEntity", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("ExpensesTracker.Data.User", b =>
                {
                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
